

export const ErrorCodes = {
  // ─── Auth (existing) ───────────────────────────────────────
  AUTH_INVALID_CREDENTIALS: "AUTH_001",
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_002",
  AUTH_TOKEN_EXPIRED: "AUTH_003",
  AUTH_TOKEN_INVALID: "AUTH_004",
  AUTH_UNAUTHORIZED: "AUTH_005",
  AUTH_FORBIDDEN: "AUTH_006",
  AUTH_PROVIDER_MISMATCH: "AUTH_007",

  // ─── Workspace ─────────────────────────────────────────────
  WORKSPACE_NOT_FOUND: "WORKSPACE_001",
  WORKSPACE_SLUG_CONFLICT: "WORKSPACE_002",
  WORKSPACE_FORBIDDEN: "WORKSPACE_003",

  // ─── Workspace Member ──────────────────────────────────────
  MEMBER_NOT_FOUND: "MEMBER_001",
  MEMBER_ALREADY_EXISTS: "MEMBER_002",
  MEMBER_ROLE_FORBIDDEN: "MEMBER_003",
  MEMBER_LAST_OWNER: "MEMBER_004",

  // ─── Project ───────────────────────────────────────────────
  PROJECT_NOT_FOUND: "PROJECT_001",
  PROJECT_KEY_CONFLICT: "PROJECT_002",
  PROJECT_FORBIDDEN: "PROJECT_003",

  // ─── Invitation ────────────────────────────────────────────
  INVITATION_NOT_FOUND: "INVITE_001",
  INVITATION_EXPIRED: "INVITE_002",
  INVITATION_ALREADY_ACCEPTED: "INVITE_003",
  INVITATION_REVOKED: "INVITE_004",
  INVITATION_ALREADY_MEMBER: "INVITE_005",

  // ─── General (existing) ────────────────────────────────────
  NOT_FOUND: "GENERAL_001",
  VALIDATION_ERROR: "GENERAL_002",
  INTERNAL_SERVER_ERROR: "GENERAL_003",


  ISSUE_NOT_FOUND: "ISSUE_001",
  ISSUE_INVALID_PARENT: "ISSUE_002",
  ISSUE_INVALID_TRANSITION: "ISSUE_003",
  ISSUE_FORBIDDEN: "ISSUE_004",



SPRINT_NOT_FOUND:          "SPRINT_001",
SPRINT_ALREADY_ACTIVE:     "SPRINT_002",
SPRINT_NOT_ACTIVE:         "SPRINT_003",
SPRINT_ALREADY_COMPLETED:  "SPRINT_004",
SPRINT_DATES_INVALID:      "SPRINT_005",


COMMENT_NOT_FOUND:   "COMMENT_001",
COMMENT_FORBIDDEN:   "COMMENT_002",


NOTIFICATION_NOT_FOUND: "NOTIF_001",
NOTIFICATION_FORBIDDEN: "NOTIF_002",
};

